### ISSUE TITLE
"Creating a Real-time Analysis Plugin" is linked twice

### ISSUE THREAD

**Issue by badboy** [mozilla/firefox-data-docs#103]
The "Creating a Real-time Analysis Plugin" is linked twice in the ToC, once under Tools/Interfaces and once under Cookbooks.
This might confuse users and it also confuses gitbook, as the "next chapter" link will always point to the (currently empty) "Distribution Viewer" chapter (and not the "Longitudinal Examples" chapter if going through the cookbook section).

**Comment by badboy** [comment]
The same is true for:
* "Getting Started / Choosing a Dataset" and "Understanding your data / Choosing a Dataset"
* "Getting Started / Common Analysis Gotchas" and "Understanding your data / Common Analysis Gotchas"

**Comment by harterrt** [comment]
Thanks for reporting this, Jan-Erik.

This is intentional. We want the documentation to be available wherever it is relevant. I agree that the "Next Chapter" behavior is a bug. I'd sooner disable this functionality, though.
