### ISSUE TITLE
document socorro_crash dataset

### ISSUE THREAD

**Issue by willkg** [mozilla/firefox-data-docs#136]
Socorro is the crash ingestion pipeline for submitted crash reports. Socorro exports a subset of that data which is pulled into Telemetry daily/nightly. I think it's the `socorro_crash` dataset.

It'd be great to have that data set covered in this documentation.

**Comment by acmiyaguchi** [comment]
I've worked on automating the ingestion of the crash reports, I can add in a few details about where the parts are and how to access the dataset.

**Comment by willkg** [comment]
Thank you! Let me know if you need any help.

**Comment by willkg** [comment]
I think #143 covers the need here and we can close it out now.
