### ISSUE TITLE
Add guide to plotting data in Jupyter

### ISSUE THREAD

**Issue by harterrt** [mozilla/firefox-data-docs#14]
As requested in #telemetry, it would be useful to have a guide to plotting/visualizing telemetry data from Jupyter notebooks.

**Comment by mreid-moz** [comment]
cc @Dexterp37 because he put together a great presentation on this topic.

**Comment by Dexterp37** [comment]
I might be able to start writing this. Should it focus on some specific need/library? Or generally how to plot stuff from Pandas/rdd/numpy using matplotlib?

**Comment by harterrt** [comment]
Thanks, Dexter! I think the latter (plotting with pandas/rdd/numpy) would be best. This document if for someone who's new to ATMO/Jupyter/Spark who just pulled some data using Spark but has no idea how to start visualizing.

**Comment by Dexterp37** [comment]
Ok, taking this bug as I'm planning to sketch things out in the upcoming weeks :) I'm also planning to add a DOs and DONTs section for best practices about plots.

Sidenote: I'm not sure why github didn't notify me about your comment :S

**Comment by Dexterp37** [comment]
Unassigning as I has no time to work on this for a while, though it's still on my radar.

**Comment by wlach** [comment]
Let's just close this one, there are many tutorials for this sort of thing online already. Can always reopen if we identify a specific need.
