### ISSUE TITLE
Add cookbook for Event Design

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/firefox-data-docs#142]
Chatting with the Project Savant folks has been illuminating in terms of some of the best practices & common pitfalls around designing an event taxonomy -- we should encapsulate those and add them as a cookbook

**Comment by harterrt** [comment]
Do you have a guess at priority, @sunahsuh ?

**Comment by sunahsuh** [comment]
P2 (I have the barest of docs started but Su has agreed to review a draft/add comments :))

**Comment by SuYoungHong** [comment]
hi guys, update, I wrote a proposal doc for some changes to either the Events API or in guidelines / requirements for implementing events with the current API: 

https://docs.google.com/document/d/1ZcKaTEXx8MWrqp2xXU8xModbvFo30UPig0hLekvMx94/edit

I think it make sense to resolve these first and nail it down before writing best practices. 

Please review and let me know if it sounds reasonable / feasible

- Su

**Comment by wlach** [comment]
Moving to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631940
