### ISSUE TITLE
Dataset TOCs seem to be broken

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/firefox-data-docs#149]
The Table of Contents at the beginning of the [`Choosing a dataset`](https://docs.telemetry.mozilla.org/concepts/choosing_a_dataset.html) page seems to be broken: clicking on any link doesn't navigate to the related section.

**Comment by mreid-moz** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1408048
