### ISSUE TITLE
Add top level TMO navigation

### ISSUE THREAD

**Issue by georgf** [mozilla/firefox-data-docs#151]
When navigating to the docs it's a leaf in our product navigation tree, with no obvious way out to navigate to TMO or other places (without reading all the docs).

Can we add e.g. a top bar with links to at least [Telemetry portal](https://telemetry.mozilla.org/) and e.g. `#fx-metrics`?

**Comment by georgf** [comment]
To be clear, this is not a problem exclusive to DTMO, but it would be nice to fix there.

**Comment by harterrt** [comment]
Sounds great, Georg. This probably belongs in an article titled "Other resources" under "Reporting a Problem".

**Comment by georgf** [comment]
I think that doesn't solve the problem of making these obvious navigation links.
It still requires reading through some articles and identifying the right article to check.

**Comment by badboy** [comment]
@georgf probably means a top bar, e.g. something like I manually added here: ![top bar for docs](https://screenshotscdn.firefoxusercontent.com/images/4558fb5d-09e3-4807-beef-195e906c132d.png) (styling open for bikeshedding).

A top bar might be possible to add by [extending the current theme](https://toolchain.gitbook.com/themes/).

**Comment by harterrt** [comment]
Can we add a section to the root page instead of creating a top bar?

**Comment by harterrt** [comment]
I think looking at the sidebar for an "External Resources" article is a reasonable barrier to discoverability.

The external links are only relevant for some of DTMO's content. I'd like to avoid adding too much content to the header. I'd also like to avoid maintaining a custom theme.

**Comment by wlach** [comment]
Moving to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631937
