### ISSUE TITLE
Add Documentation on Running Spark Jobs on a Cluster Using Telemetry Batch View

### ISSUE THREAD

**Issue by erindorothy** [mozilla/firefox-data-docs#156]
As I have been trying to run Spark Jobs on clusters, I've noticed that more documentation could be helpful for new interns or new hires. So far, I have been keeping track of the steps I have been taking to do this, and would like to contribute my documentation if needed.

**Comment by harterrt** [comment]
Sorry for the slow reply, Erin. That would be great! Do you have rough drafts of this documentation anywhere?

**Comment by wlach** [comment]
Closing this as the content (even if we could get it now) would not be relevant in a GCP world. No worries!
