### ISSUE TITLE
Coverage for mobile

### ISSUE THREAD

**Issue by dzeber** [mozilla/firefox-data-docs#157]
Currently the coverage of datasets is primarily focused on desktop. As mobile becomes more of a priority and people look for information about mobile data, it would be good to add some comments making clear which portions of the documentation do or do not apply to mobile.

**Comment by harterrt** [comment]
Adding @mmccorks as a CC

**Comment by wlach** [comment]
Moving to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631936
