### ISSUE TITLE
Document History Order

### ISSUE THREAD

**Issue by badboy** [mozilla/firefox-data-docs#170]
Document how to order history in the new profile history documentation

**Comment by Michelleui** [comment]
how to know from the ipadress which phone model is is on it;

**Comment by Michelleui** [comment]
may i knoe who can give me a good API

**Comment by badboy** [comment]
@Michelleui I have no idea what you are talking about and this issue seems unrelated to whatever you are asking. I don't think this is the right place for these questions.

**Comment by wlach** [comment]
Moving to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631934
