### ISSUE TITLE
Extend "History Has No Beginning"

### ISSUE THREAD

**Issue by badboy** [mozilla/firefox-data-docs#171]
With #165 merged, the documentation will read:

> In this example, the profile simply appears in our data mid-history, with presumably the 25th subsession in it's history. Its previous history is a mystery.

@chutten noted:

> It might be worth mentioning that losing the first pings in the history is indistinguishable from having a user whose profile creation happened before the data horizon.

Let's phrase that nicely and add it.

**Comment by wlach** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631895
