### ISSUE TITLE
History Restarts: Document behavior on profile reset

### ISSUE THREAD

**Issue by badboy** [mozilla/firefox-data-docs#172]
When #165 lands we have documentation about "History restarts" and how that looks in the data.

@chutten noted:

> I think it would be worth stating that this is what a profile reset looks like. To verify that it is a profile reset, the `profile_reset_date` should be set to a value on or before the `subsession_start_date` of the ping that has the `profile_subsession_counter` of 1 and the null `previous_subsession_id`

**Comment by wlach** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631918
