### ISSUE TITLE
Realworld usage: Infrequency of migrations and how narrow queries don't see them

### ISSUE THREAD

**Issue by badboy** [mozilla/firefox-data-docs#174]
@chutten notes:

> Might it be worth highlighting that Migrations are likely infrequent and so our ability to identify them is hampered by how most of our datasets and queries use relatively-narrow time ranges?

**Comment by wlach** [comment]
Moving to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631916
