### ISSUE TITLE
Document the data flow of the client-side Firefox Telemetry Architecture

### ISSUE THREAD

**Issue by chutten** [mozilla/firefox-data-docs#175]
During the Firefox Telemetry work week in Berlin earlier this month we realized that we were missing a client-side architecture diagram (with an emphasis on data flow) that would be helpful to have as a resource.

To draw from as inspiration we have Georg's very-high-level "What We Own" [data-flow diagram](https://docs.google.com/document/d/15ZwsVj9QKnPEB2F6fUpjnfEPT9pTo6cWwkkAMZB18vE/edit#heading=h.5d0e94fxznql) from that session.

The resolution of this diagram would be a little finer than that one, and the audience would be fx-data-platform.

**Comment by wlach** [comment]
Moving to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631915
