### ISSUE TITLE
Tracking: Move additional preprocessors to upstream

### ISSUE THREAD

**Issue by badboy** [mozilla/firefox-data-docs#186]
We will move over to mdbook (as per #162).
For this we can use [mdbook-dtmo](https://github.com/badboy/mdbook-dtmo), a wrapper around additional preprocessors.
It would be nice if we don't need to fully wrap mdbook, but instead if provides these preprocessors or an easier plugin system for it.

Relevant upstream issues:

- [provide mermaidjs rendering](https://github.com/rust-lang-nursery/mdBook/issues/762)
- [Custom preprocessors](https://github.com/rust-lang-nursery/mdBook/pull/792)

**Comment by wlach** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631913
