### ISSUE TITLE
Live link check

### ISSUE THREAD

**Issue by badboy** [mozilla/firefox-data-docs#195]
While our [current link check](https://github.com/mozilla/firefox-data-docs/blob/40ecaf41882d3566a1699e85485b4afe2bfc59b2/scripts/link_check.sh) works decently, it only checks that external links and links to local markdown files are correct.

However, at some points we do include files into other files, breaking relative links. The only proper way to do this is to run a link check on the generated book.

We should investigate if we can automate that on CI.

**Comment by wlach** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631912
