### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by wcbeard** [mozilla/firefox-data-docs#27]
I came across some dead links, but could only find replacements for some. I hear there may be a lot of changes to the docs this week, but just in case, here are all of the ones that returned 404 from a script

- concepts/data_pipeline.md
    - don't see replacement for https://github.com/mozilla-services/puppet-config/tree/02f716a3e0df1117fc2494b41e85a1416f8e2a64/pipeline

- https://python-moztelemetry.readthedocs.io/en/stable/userguide.html
	- there's no userguide.html, just api.html. There were links in
tools/hbase.md, concepts/data_pipeline.md and datasets/ping_intro.md

- cookbooks/longitudinal_examples.md (I see no examples folder anymore)
    - https://github.com/mozilla/emr-bootstrap-spark/blob/master/examples/Longitudinal%20Dataset%20Tutorial.ipynb

- datasets/batch_view/addons/reference.md
    - https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/views/AddonsView.scala
	    - perhaps this? https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/com/mozilla/telemetry/views/AddonsView.scala

- datasets/batch_view/client_count/intro.md
    - https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala#L22
        - file removed in https://github.com/mozilla/telemetry-batch-view/commit/2377a5d02917ccbf87ab2ada9bc65f19fc7a02c8

**Comment by harterrt** [comment]
Gah, I hate dead links. Can you share the script you used to detect these links? I'd like to add some CI for the docs.

**Comment by wcbeard** [comment]
Sure, [here's a cleaned up version](https://gist.github.com/wcbeard/a639235c35bfc4f70d5c92e0c0b26124). You may need to apply some heuristics to avoid e.g. `https://localhost:8888` urls. Not sure what can be done for links behind LDAP though.

**Comment by harterrt** [comment]
Tracking the dead link CI here: https://bugzilla.mozilla.org/show_bug.cgi?id=1384110

Let's leave this open until all of these links are fixed.

**Comment by harterrt** [comment]
w00t
