### ISSUE TITLE
clients_last_seen examples don't run

### ISSUE THREAD

**Issue by tdsmith** [mozilla/firefox-data-docs#273]
The `clients_last_seen` examples use a `last_seen_date` column, which doesn't seem to exist; have those been replaced by `days_since_seen`? cc @relud

**Comment by relud** [comment]
you are correct. will fix Monday

**Comment by relud** [comment]
>_< accidentally committed the fix directly to master. fixed though.

**Comment by tdsmith** [comment]
Thank you!
