### ISSUE TITLE
Dead link to firefox-test-tube.herokuapp.com

### ISSUE THREAD

**Issue by georgf** [mozilla/firefox-data-docs#277]
The CI run for #276 failed due to:
> FILE: src/datasets/shield.md
> [✖] https://firefox-test-tube.herokuapp.com/ → Status: 404

**Comment by georgf** [comment]
@rafrombrc for next steps here?

**Comment by robhudson** [comment]
The front-end was removed recently...
See: https://github.com/mozilla/firefox-test-tube/commit/12dfa175dd2dee59abc36da37425f445d292ca70

**Comment by jaredkerim** [comment]
The functionality of Test Tube is being replaced by the combination of Experimenter and Grafana, but users should be directed to Experimenter and Experimenter will link to the relevant Grafana dashboards.

The landing page for Experimenter is here: https://experimenter.services.mozilla.com/

And you could say something like

Experimenter is a tool for managing the lifecycle of Firefox experiments and includes the relevant links for each experiment including Bugzilla tickets and live monitoring dashboards in Grafana.

**Comment by openjck** [comment]
My apologies for not alerting you about this in advance. I forgot that dtmo linked to Test Tube.
