### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by tdsmith** [mozilla/firefox-data-docs#305]
https://docs.telemetry.mozilla.org/concepts/choosing_a_dataset.html has a broken image reference to https://docs.telemetry.mozilla.org/concepts/images/first_session_pings.png.

**Comment by mreid-moz** [comment]
cc @badboy - I'm not sure how to fix this, the image is linked from a file that's `#include`d (`ping_intro.md`) so the relative path to the image doesn't work in both places.
