### ISSUE TITLE
"Choosing a dataset" TOC isn't useful

### ISSUE THREAD

**Issue by tdsmith** [mozilla/firefox-data-docs#306]
The TOC at https://docs.telemetry.mozilla.org/concepts/choosing_a_dataset.html isn't useful.

In particular, the subheadings are just the repeated phrases "Contents / Background and Caveats / Accessing the Data".

**Comment by badboy** [comment]
Woops, looks like that is actually a bug with our mdbook-toc integration. It's missing all these headings in between.

I'll take this and fix the tool, then update here

**Comment by badboy** [comment]
Looks much more useful already:

![](https://tmp.fnordig.de/scr/9a18004246.png)

(waiting for the release to build, then I can update the data docs)

**Comment by badboy** [comment]
Oh actually, they will be automatically fixed with the next deploy as CI just uses the latest release

**Comment by tdsmith** [comment]
This has been fixed! Thank you :)
