### ISSUE TITLE
Document BigQuery UDFs

### ISSUE THREAD

**Issue by tdsmith** [mozilla/firefox-data-docs#312]
These live in https://github.com/mozilla/bigquery-etl/tree/master/udf and https://github.com/mozilla/bigquery-etl/tree/master/udf_js.

Should the documentation be authored in that tree or this one? Should it be published with DTMO or should we just link out to it?

**Comment by tdsmith** [comment]
cf https://github.com/mozilla/bigquery-etl/issues/228

**Comment by jklukas** [comment]
This looks like largely a duplicate of #228, so closing. But I will add a note on DTMO linking to #228 as a future improvement.
