### ISSUE TITLE
Blocklist last-update is now collected

### ISSUE THREAD

**Issue by tdsmith** [mozilla/firefox-data-docs#332]
as of [bug 1574441](https://bugzilla.mozilla.org/show_bug.cgi?id=1574441), we do collect blocklist last-update, which made a liar out of https://docs.telemetry.mozilla.org/concepts/censuses.html.

**Comment by wlach** [comment]
Moving this to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631910
