### ISSUE TITLE
CI failing due to mdbook install being broken

### ISSUE THREAD

**Issue by jklukas** [mozilla/firefox-data-docs#345]
It looks like all PRs are failing CI with:

> The command "curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git rust-lang-nursery/mdBook" failed and exited with 2 during .

It looks like japaric.github.io no longer exists.

cc @badboy

**Comment by badboy** [comment]
Oh wait, [this](https://travis-ci.org/mozilla/firefox-data-docs/builds/605522826) is failing due to other problems.

**Comment by badboy** [comment]
ah problem identified, PR incoming

**Comment by badboy** [comment]
Should be fixed now after #346 landed.
