### ISSUE TITLE
Update to v4 schema in main summary

### ISSUE THREAD

**Issue by wcbeard** [mozilla/firefox-data-docs#36]
The previous v3 schema is listed [here](https://github.com/mozilla/firefox-data-docs/blob/master/datasets/batch_view/main_summary/reference.md#schema) "As of 2016-07-05", might be worth updating.

Not sure when the new one went into effect, but I think [this should be it](https://gist.github.com/wcbeard/89df0b3a6a3c8742ad7c10d5e7501d21) (I included the code snippet I used to generate it).

**Comment by mreid-moz** [comment]
This was resolved by #51
