### ISSUE TITLE
Search dataset documentation need to be updated for gcp

### ISSUE THREAD

**Issue by wlach** [mozilla/firefox-data-docs#367]
There are still references to presto, python_mozetl, etc.:

https://docs.telemetry.mozilla.org/datasets/search.html

**Comment by wlach** [comment]
@Ben-Wu is this something you could handle, since you're closest to the new implementation? I don't think it should take too long.

**Comment by Ben-Wu** [comment]
Yes I can do this later if it doesn't get updated in #366
