### ISSUE TITLE
update the "Normandy client getting started" docs

### ISSUE THREAD

**Issue by shell1** [mozilla/firefox-data-docs#379]
These docs need to be updated to reduce avoidable errors - especially since feature gate hasn't been broadly advised, multi-pref experiments exist, and branched add-ons exist.     https://docs.telemetry.mozilla.org/cookbooks/client_guidelines.html

I put a doc together with what I think needs to change - but I 1) don't know how to change docs in DTMO and 2) need technical review. https://docs.google.com/document/d/1Je8k9wZxsr3Uu8zWD2-U9jcB9UlFmq3cxoDTfMVzJ7I/edit#heading=h.7n7hrx1v4x7z

**Comment by shell1** [comment]
filed this issue and to take to our meeting today so rehan and mythmon can weigh in on changes and then submit them.

**Comment by wlach** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631906
