### ISSUE TITLE
Add example for working with dynamic probes (scalar/histograms) in main_summary

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/firefox-data-docs#406]
Searching for `dynamic scalar` leads to the main_summary page here:

https://github.com/mozilla/firefox-data-docs/blob/master/src/datasets/batch_view/main_summary/reference.md#schema

An example of how to access a scalar field in main_summary would make this information more actionable.

**Comment by wlach** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1631892
