### ISSUE TITLE
Add example for how to work with key-value maps/structs in bigquery

### ISSUE THREAD

**Issue by ncalexan** [mozilla/firefox-data-docs#409]
Both Mike Conley and I were confused by the representation of, say, `environment` maps in `telemetry.main`.  It would help to be very clear on how to do this in the onboarding docs, since most Firefox engineers coming to STMO are trying to get at this type of data.

From a conversation in #fx-metrics:

- mconley: Hey folks. Dusting off my STMO skills, and boy are they rusty. Suppose I’m querying the telemetry.main database, and I want to access some of the fields inside of payload.simple_measurements. simple_measurements is coming back looking similar to: `	
{“f”:[{“v”:“1”},{“v”:“623”},{“v”:null},{“v”:“290"},{“v”:null},{“v”:“3”}]}`… how do I derive meaning from it? Is there a function that’ll convert that into a map that I can access for things like `sessionRestored` time?
- tdsmith: So, this is how re:dash visualizes structs, which is not super-helpful.  You can access the members directly like `SELECT payload.simple_measurements.session_restored`

tdsmith suggested: FWIW, the script I keep around to enumerate struct members on an entire table is
```
bq show --schema $1 | jq -r '.[] | recurse(.fields[]? + {parent: ((.parent? // []) + [.name])}) | .parent + [.name] | join(".")'
```
for `$1` like `moz-fx-data-shared-prod:telemetry.main`

esmyth suggested: FWIW, I typically unnest the struct. e.g., the `environment.system.gfx.adaptors` repeated record on `telemetry.main`
```
FROM `moz-fx-data-derived-datasets.telemetry.main`
    LEFT JOIN UNNEST(environment.system.gfx.adapters) AS gfx_adapters
```

**Comment by wlach** [comment]
Moving to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631904
