### ISSUE TITLE
Document FxA BigQuery Tables

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/firefox-data-docs#411]
Data Eng maintains tables of FxA server-side event metrics, such as those seen in the screenshot below.. 
<img width="333" alt="image" src="https://user-images.githubusercontent.com/5625313/74785165-e2985f80-5266-11ea-9ed1-62dabfd49aed.png">

We should really document these, as more and more people are using them. I suppose this would be on me.

**Comment by irrationalagent** [comment]
@ksiegler1 to help with this too

**Comment by wlach** [comment]
Moving to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631894
