### ISSUE TITLE
Document Best Practices for Dashboards

### ISSUE THREAD

**Issue by chutten** [mozilla/firefox-data-docs#420]
In a conversation on Slack, :wlach mentioned that basically every dashboard filters aggregates based on some threshold of interest. If every dashboard does it, maybe we should document that. But where? 

Maybe for now in Analysis Gotchas, but maybe later we need a Best Practices area.

Content-wise maybe some back-of-the-envelope stuff like "Ignore any geography with fewer than 15k clients, any build not in buildhub (or with fewer than 1k users)"

**Comment by wlach** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631896
