### ISSUE TITLE
Document bigquery-etl public dataset workflow

### ISSUE THREAD

**Issue by wlach** [mozilla/firefox-data-docs#429]
[This proposal](https://docs.google.com/document/d/1zJtRTiiBxpE6faf-HNL6IVTXIFHXvceKCxWXYM0wf9w/edit#) has been accepted and implemented in bigquery-etl, but we have no documentation on this. 

This could go in the "operational cookbooks" section, similar to the bigquery-airflow doc: https://docs.telemetry.mozilla.org/cookbooks/bigquery-airflow.html

**Comment by scholtzan** [comment]
I'll write up some documentation once JSON publish support lands.
