### ISSUE TITLE
Page TOCs rendering funny

### ISSUE THREAD

**Issue by tdsmith** [mozilla/firefox-data-docs#450]
There's a couple pages where the TOCs render funny, e.g. https://docs.telemetry.mozilla.org/datasets/other/attitudes_daily/reference.html, and https://docs.telemetry.mozilla.org/datasets/batch_view/telemetry_aggregates/reference.html

<img width="735" alt="image" src="https://user-images.githubusercontent.com/173889/79601986-8e5eff80-809e-11ea-89a8-347f91755b1a.png">

I think not all of those things should be on the first line.

**Comment by jklukas** [comment]
It looks like any intro with fourth-level headers `####` is affected by this.

**Comment by jklukas** [comment]
The important piece may be fourth-level headings appearing without a third-level heading. The following renders fourth-level headings reasonably in the toc:

https://docs.telemetry.mozilla.org/datasets/pings.html

**Comment by wlach** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631897
