### ISSUE TITLE
Update the "Delays" section of gotchas

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/firefox-data-docs#59]
The [Delays](https://docs.telemetry.mozilla.org/concepts/analysis_gotchas.html#delays) section of the docs should be updated per the [latest and greatest recommendations](https://chuttenblog.wordpress.com/2017/07/12/latency-improvements-or-yet-another-satisfying-graph/).

**Comment by harterrt** [comment]
@chutten can you take this?

**Comment by harterrt** [comment]
Should be addressed with https://github.com/mozilla/firefox-data-docs/pull/81
