### ISSUE TITLE
Add docs for scheduling airflow tasks

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/firefox-data-docs#70]
Currently we only have a few mentions of airflow but no details re: scheduling new airflow tasks/dags

**Comment by harterrt** [comment]
@fbertsch - FYI, may be good to tackle this long-standing bug as you document the Airflow staging environment workflow 

...:crossed_fingers:

**Comment by fbertsch** [comment]
I think that makes sense. I'll try and get to it this Q.

**Comment by wlach** [comment]
Moving to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631946
