### ISSUE TITLE
Add mermaid support

### ISSUE THREAD

**Issue by georgf** [mozilla/firefox-data-docs#78]
I did a [quick test](http://bit.ly/2CKO1P2) of [mermaid](https://mermaidjs.github.io/) and it seems convenient for building graphs.
That would be convenient for visualizing architecture, data-flow etc.

I see there are some gitbook plugins for mermaid, [like this](https://github.com/JozoVilcek/gitbook-plugin-mermaid).
Could we add one to the setup here?

**Comment by mreid-moz** [comment]
Resolved by #79
