### ISSUE TITLE
Explain / describe file structure in either README or in meta/contributing.

### ISSUE THREAD

**Issue by gregglind** [mozilla/firefox-data-docs#90]

**Comment by mreid-moz** [comment]
Is this information sufficient?
https://docs.telemetry.mozilla.org/meta/structure.html

**Comment by gregglind** [comment]
(Sorry, I claim it's not, because it's not in the README :)  I wouldn't know to get to meta/structure :) )

**Comment by harterrt** [comment]
Solid point. Starting https://github.com/mozilla/firefox-data-docs/pull/97 to address this.
